# Run Scripts with `bx <script-name>`

version = "0.3.2"

[scripts]
    # Build commands
    build.cmd          = "cargo build"
    build.desc         = "Build debug binary"
    build-release.cmd  = "cargo build --release"
    build-release.desc = "Build release binary"
    prod.cmd           = "cargo build --release"
    prod.desc          = "Shortcut for building the release binary"

    # Run/test the supervisor
    run.cmd  = "cargo run -- %%"
    run.desc = "Run supi-cli with arguments, e.g.: bx run echo hello"

    dev.cmd  = "cargo run -- echo 'Hello from supervised process'"
    dev.desc = "Quick dev test - runs echo command under supervision"

    # Test with actual long-running process
    dev-sleep.cmd  = "cargo run -- -- bash -c 'while true; do echo tick; sleep 1; done'"
    dev-sleep.desc = "Test with infinite loop process (press 'r' to restart, Ctrl+C to stop)"

    # Testing commands
    test.cmd        = "cargo test -- --nocapture %%"
    test.desc       = "Run all tests (without argument) or specific test (with test fn name as arg)"
    test-watch.cmd  = "cargo watch -x 'test -- --nocapture'"
    test-watch.desc = "Watch mode for tests"

    # Utility commands
    check.cmd  = "cargo check"
    check.desc = "Quick check for compilation errors"

    clippy.cmd  = "cargo clippy"
    clippy.desc = "Run clippy linter"

    fmt.cmd  = "cargo fmt"
    fmt.desc = "Format code with rustfmt"

    # Shortcuts for testing supi-cli commands
    helpArg.cmd        = "cargo run -- --help"
    helpArg.desc       = "Show supi-cli help"
    versionArg.cmd     = "cargo run -- --version"
    versionArg.desc    = "Show supi-cli version"
    V.cmd              = "cargo run -- -V"
    V.desc             = "Show supi-cli version"
    sleep.cmd          = "cargo run -- bash -- -c 'sleep 10 && echo \"Slept 10 seconds, command completed\"'"
    sleep.desc         = "Run sleep 10 seconds and echo completion"
    colorExample.cmd   = "cargo run -- --log-color red --info-color blue echo 'Hello from supervised process'"
    colorExample.desc  = "Run echo command with red log color and blue info color"
    silentExample.cmd  = "cargo run -- --silent bash -- -c 'for i in {1..5}; do echo \"Output $i\"; sleep 1; done'"
    silentExample.desc = "Run with --silent flag (only child output visible, no supervisor messages)"
